# Generated by Django 5.2 on 2025-04-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_paciente_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='historico_medico',
            new_name='historico',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.TextField(),
        ),
    ]
