# Generated by Django 5.2 on 2025-04-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_rename_historico_medico_paciente_historico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='historico',
            field=models.TextField(default='Sem histórico'),
            preserve_default=False,
        ),
    ]
