# Generated by Django 5.2 on 2025-04-21 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='data_agendamento',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='resultado',
        ),
        migrations.AddField(
            model_name='exame',
            name='data_exame',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
